In [27]:
import sys
import numpy as np
import math

In [28]:
class primitive_gaussian():
    
    def __init__(self, alpha, coeff, coordinates, l1, l2, l3):
        self.alpha = alpha
        self.coeff = coeff
        self.coordinates = np.array(coordinates)
        self.A = (2.0 * alpha / math.pi) ** (3/4)

In [29]:
def overlap(molecule):

    nbasis = len(molecule)

    S = np.zeros([nbasis, nbasis])

    for i in range(nbasis):
        for j in range(nbasis):

            nprimitives_i = len(molecule[i])
            nprimitives_j = len(molecule[j])

            for k in range(nprimitives_i):
                for l in range(nprimitives_j):

                    N = molecule[i][k].A * molecule[j][l].A
                    p = molecule[i][k].alpha + molecule[j][l].alpha
                    q = molecule[i][k].alpha * molecule[j][l].alpha / p
                    Q = molecule[i][k].coordinates - molecule[j][l].coordinates
                    Q2 = np.dot(Q,Q)

                    S[i,j] += N * molecule[i][k].coeff * molecule[j][l].coeff * math.exp(-q*Q2) * (math.pi/p)**(3/2)
    
    return S

In [30]:
def kinetic(molecule):

    nbasis = len(molecule)

    T = np.zeros([nbasis, nbasis])

    for i in range(nbasis):
        for j in range(nbasis):

            nprimitives_i = len(molecule[i])
            nprimitives_j = len(molecule[j])

            for k in range(nprimitives_i):
                for l in range(nprimitives_j):

                    c1c2 = molecule[i][k].coeff * molecule[j][l].coeff

                    N = molecule[i][k].A * molecule[j][l].A
                    p = molecule[i][k].alpha + molecule[j][l].alpha
                    q = molecule[i][k].alpha * molecule[j][l].alpha / p
                    Q = molecule[i][k].coordinates - molecule[j][l].coordinates
                    Q2 = np.dot(Q,Q)

                    P = molecule[i][k].alpha*molecule[i][k].coordinates + molecule[j][l].alpha*molecule[j][l].coordinates
                    Pp = P/p
                    PG = Pp - molecule[j][l].coordinates
                    PGx2 = PG[0]*PG[0]
                    PGy2 = PG[1]*PG[1]
                    PGz2 = PG[2]*PG[2]

                    s = N * c1c2 * math.exp(-q*Q2) * (math.pi/p)**(3/2)

                    T[i,j] += 3*molecule[j][l].alpha*s
                    T[i,j] -= 2*molecule[j][l].alpha*molecule[j][l].alpha * s * (PGx2 + 0.5/p)
                    T[i,j] -= 2*molecule[j][l].alpha*molecule[j][l].alpha * s * (PGy2 + 0.5/p)
                    T[i,j] -= 2*molecule[j][l].alpha*molecule[j][l].alpha * s * (PGz2 + 0.5/p)
    
    return T

In [31]:
# STO-3G basis for 1s orbital on hydrogen
H1_pg1a = primitive_gaussian(0.3425250914E+01, 0.1543289673E+00, [0,0,0], 0, 0, 0)
H1_pg1b = primitive_gaussian(0.6239137298E+00, 0.5353281423E+00, [0,0,0], 0, 0, 0)
H1_pg1c = primitive_gaussian(0.1688554040E+00, 0.4446345422E+00, [0,0,0], 0, 0, 0)
H2_pg1a = primitive_gaussian(0.3425250914E+01, 0.1543289673E+00, [1.4,0,0], 0, 0, 0)
H2_pg1b = primitive_gaussian(0.6239137298E+00, 0.5353281423E+00, [1.4,0,0], 0, 0, 0)
H2_pg1c = primitive_gaussian(0.1688554040E+00, 0.4446345422E+00, [1.4,0,0], 0, 0, 0)
H1_1s = [H1_pg1a, H1_pg1b, H1_pg1c]
H2_1s = [H2_pg1a, H2_pg1b, H2_pg1c]
molecule = [H1_1s, H2_1s]
print("\nSTO-3G basis for H2:")
print("Overlap Matrix:\n", overlap(molecule))
print("Kinetic Energy Matrix:\n", kinetic(molecule))


# 6-31G basis for 1s and 2s orbitals on hydrogen

H1_pg1a = primitive_gaussian(0.1873113696E+02, 0.3349460434E-01, [0,0,0], 0, 0, 0)
H1_pg1b = primitive_gaussian(0.2825394365E+01, 0.2347269535E+00, [0,0,0], 0, 0, 0)
H1_pg1c = primitive_gaussian(0.6401216923E+00, 0.8137573261E+00, [0,0,0], 0, 0, 0)
H1_pg2a = primitive_gaussian(0.1612777588E+00, 1.0000000, [0,0,0], 0, 0, 0)

H2_pg1a = primitive_gaussian(0.1873113696E+02, 0.3349460434E-01, [1.2,0,0], 0, 0, 0)
H2_pg1b = primitive_gaussian(0.2825394365E+01, 0.2347269535E+00, [1.2,0,0], 0, 0, 0)
H2_pg1c = primitive_gaussian(0.6401216923E+00, 0.8137573261E+00, [1.2,0,0], 0, 0, 0)
H2_pg2a = primitive_gaussian(0.1612777588E+00, 1.0000000, [1.2,0,0], 0, 0, 0)
H1_1s = [H1_pg1a, H1_pg1b, H1_pg1c]
H1_2s = [H1_pg2a]
H2_1s = [H2_pg1a, H2_pg1b, H2_pg1c]
H2_2s = [H2_pg2a]

molecule = [H1_1s, H1_2s, H2_1s, H2_2s]
print("\n6-31G basis for H2:")
print("Overlap Matrix:\n", overlap(molecule))
print("Kinetic Energy Matrix:\n", kinetic(molecule))



STO-3G basis for H2:
Overlap Matrix:
 [[1.         0.65931821]
 [0.65931821 1.        ]]
Kinetic Energy Matrix:
 [[0.76003188 0.23645466]
 [0.23645466 0.76003188]]

6-31G basis for H2:
Overlap Matrix:
 [[1.         0.65829197 0.55310378 0.54474596]
 [0.65829197 1.         0.54474596 0.89036838]
 [0.55310378 0.54474596 1.         0.65829197]
 [0.54474596 0.89036838 0.65829197 1.        ]]
Kinetic Energy Matrix:
 [[1.39567838 0.259735   0.36424713 0.18760875]
 [0.259735   0.24191664 0.18760875 0.19872049]
 [0.36424713 0.18760875 1.39567838 0.259735  ]
 [0.18760875 0.19872049 0.259735   0.24191664]]
